config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root 'projects#index'

  resources :projects do
    resources :categories do
      resources :products
    end

    resources :bill_types
    resources :incomes

    resources :bills do
      resources :bill_rows
    end
  end

  resources :contacts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bill.rb
class Bill < ApplicationRecord

  belongs_to :project
  belongs_to :bill_type
  belongs_to :contact
  has_many :bill_rows
  has_many :payments

  def paid?
    self.paid = self.payments.calculate(:sum, :payment_amount) < self.total_amount ? false : true
    self.paid
  end

end

app/models/bill_type.rb
class BillType < ApplicationRecord

  has_many :bills
  belongs_to :project

  validates :name, presence: true

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_bill, only: [:show, :edit, :update, :destroy]


  # GET /bills
  # GET /bills.json
  def index
    @months_to_show = 4
    @current_month = get_current_month(params[:current_month], params[:prev_link], params[:next_link])
    month = Date.new(@current_month.last.to_i, @current_month.first.to_i)
    @bills = Bill.where({project: @project, purchase_date: month.beginning_of_month..month.end_of_month})
    @bills_by_month = get_bills_by_month
  end

  def get_current_month(current_month_param, prev_link_param, next_link_param)
    month = current_month_param.present? ? current_month_param.try(:split, '-') : [Date.today.month, Date.today.year]
    month = Date.new(month.last.to_i, month.first.to_i)
    if prev_link_param.present? || next_link_param.present?
      month = prev_link_param.present? ? month.prev_month(@months_to_show) : month.next_month(@months_to_show)
    end
    [month.month, month.year]
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    @bill_rows = @bill.bill_rows
    @bill_row = BillRow.new
    @bill_row.amount = 1
    @allowed_products = Product.where(category: @project.categories).order(:name, :category_id)
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
    @allowed_products = Product.where(category: @project.categories).order(:name, :category_id)
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        set_project_total
        format.html { redirect_to project_bill_path(@project, @bill), notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        set_project_total
        format.html { redirect_to project_bill_path(@project, @bill), notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    set_project_total
    respond_to do |format|
      format.html { redirect_to project_bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_bills_by_month
    number_of_months = @months_to_show
    data = []
    while number_of_months > 0
      month = Date.new(@current_month.last.to_i, @current_month.first.to_i).prev_month(number_of_months)
      bills = Bill.where({project: @project, purchase_date: month.beginning_of_month..month.end_of_month})
      total = bills.calculate(:sum, :total_amount)
      data << {month: month, bills_count: bills.count, total: total}
      number_of_months = number_of_months - 1
    end
    data
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
      @allowed_project_contacts = Contact.all
      @allowed_project_bill_types = @project.bill_types
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(
          :project_id, :total_amount, :purchase_date, :contact_id, :bill_type_id,
          'purchase_date(1i)', 'purchase_date(2i)', 'purchase_date(3i)', :current_month
      )
      {
         project_id: @project.id,
         purchase_date: get_date(params[:bill]),
         contact_id: params[:bill][:contact_id],
         bill_type_id: params[:bill][:bill_type_id]
      }
    end

    def get_date(params)
      Date.civil(params['purchase_date(1i)'].to_i, params['purchase_date(2i)'].to_i, params['purchase_date(3i)'].to_i)
    end

  def set_project_total
    @project.total = @project.bills.calculate(:sum, :total_amount)
    @project.save
  end

end

app/helpers/bills_helper.rb
module BillsHelper

  def get_product_name(bill_row)
    Product.find(bill_row.product_id).name || ''
  end

  def get_bill_categories(bill)
    rows = bill.try(:bill_rows) || []
    categories = []
    rows.each do |bill_row|
      categories << (bill_row.try(:product).try(:category).try(:name) || '')
    end
    categories.uniq.join(' / ')
  end

  def show_next_month_option(current_month)
    Date.new(current_month.last.to_i, current_month.first.to_i).at_beginning_of_month < Date.today.at_beginning_of_month
  end

  def get_link_month(month)
    "#{month.month}-#{month.year}"
  end

  def get_prev_next_link_month(month)
    month.join('-')
  end

  def get_current_month_text(current_month)
    Date.new(current_month.last.to_i, current_month.first.to_i).strftime("%B %Y")
  end

end

app/views/bills/_bill_summary.html.erb
<div class="bill-summary">
  <div class="bill-summary-prev_month">
    <%= link_to '<< Atras', project_bills_path(@project, current_month: get_prev_next_link_month(current_month), prev_link: true) %>
  </div>
  <% bills_by_month.each do |bill_month| %>
    <div class="bill-summary-month">
      <div class="title-month"><%= link_to bill_month[:month].strftime("%B %Y"), project_bills_path(@project, current_month: get_link_month(bill_month[:month])) %></div>
      Facturas: <%= bill_month[:bills_count] %><br />
      Total Facturas: <%= bill_month[:total] %>
    </div>
  <% end %>
  <% if show_next_month_option(current_month) %>
    <div class="bill-summary-next_month">
      <%= link_to 'Siguiente >>', project_bills_path(@project, current_month: get_prev_next_link_month(current_month), next_link: true) %>
    </div>
  <% end %>
</div>

app/views/bills/_form.html.erb
<%= form_with(model: @bill, url: [@project, @bill], local: true) do |form| %>
  <% if bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="bill-section">
    <div class="bill-field">
      <%= form.label :purchase_date %>
      <%= form.date_select :purchase_date %>
    </div>

    <div class="bill-field">
      <%= form.label :contact_id %>
      <%= form.collection_select(:contact_id, @allowed_project_contacts, :id, :full_name) %>
    </div>

    <div class="bill-field">
      <%= form.label :bill_type_id %>
      <%= form.collection_select(:bill_type_id, @allowed_project_bill_types, :id, :name) %>
    </div>

    <div class="bill-field">
      <%= form.label :total_amount %>
      <%= form.number_field :total_amount, :disabled => true %>
    </div>

    <div class="bill-row-section">

    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>

  <div class="bill-row-section">
    <div class="bill-row-line">
      <div class="bill-row-field">

      </div>
    </div>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Show', project_bill_path(@project, @bill) %> |
<%= link_to 'Back', project_bills_path(@project) %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: 'bill_summary', locals: {bills_by_month: @bills_by_month, current_month: @current_month}   %>

<div class="view-content">

  <div class="title-bills-index">
    <%= get_current_month_text(@current_month) %> Bills
  </div>

  <div class="table-bills-index">

    <table>
      <thead>
        <tr>
          <th>Contact</th>
          <th>Total amount</th>
          <th>Bill type</th>
          <th>Categories</th>
          <th>Purchase date</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @bills.each do |bill| %>
          <tr>
            <td><%= link_to bill.contact.full_name, project_bill_path(@project, bill) %></td>
            <td><%= link_to (bill.total_amount || 0), project_bill_path(@project, bill) %></td>
            <td><%= link_to bill.bill_type.name, project_bill_path(@project, bill) %></td>
            <td><%= link_to get_bill_categories(bill), project_bill_path(@project, bill) %>
            <td><%= link_to bill.purchase_date, project_bill_path(@project, bill) %></td>
            <td><%= link_to 'Show', project_bill_path(@project, bill) %></td>
            <td><%= link_to 'Edit', edit_project_bill_path(@project, bill) %></td>
            <td><%= link_to 'Destroy', project_bill_path(@project, bill), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>

  <%= link_to 'New Bill', new_project_bill_path(@project) %>
</div>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Back', project_bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<div class="bill-context">

  <div class="bill-field">
    <p>
      <strong>Total amount:</strong>
      <%= @bill.total_amount %>
    </p>
  </div>

  <div class="bill-field">
    <p>
      <strong>Purchase date:</strong>
      <%= @bill.purchase_date %>
    </p>
  </div>

  <div class="bill-field">
    <p>
      <strong>Contact:</strong>
      <%= @bill.contact.full_name %>
    </p>
  </div>

  <div class="bill-field">
    <p>
      <strong>Bill type:</strong>
      <%= @bill.bill_type.name %>
    </p>
  </div>

  <div class="bill-field-buttons">
    <%= link_to 'Edit', edit_project_bill_path(@project, @bill) %> |
    <%= link_to 'Back', project_bills_path %>
  </div>
</div>
<div class="bill-rows-context">
  <div class="bill-row-table">
    <table>
      <thead>
      <tr>
        <th>Product</th>
        <th>Amount</th>
        <th>Price</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @bill_rows.each do |bill_row| %>
        <tr>
          <td><%= get_product_name(bill_row) %></td>
          <td><%= bill_row.amount %></td>
          <td><%= bill_row.price %></td>
          <td><%= link_to 'Edit', edit_project_bill_bill_row_path(@project, @bill, bill_row) %></td>
          <td><%= link_to 'Destroy', project_bill_bill_row_path(@project, @bill, bill_row), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  <div class="bill-row-form">
    <%= render 'bill_rows/form', bill_row: @bill_row %>
  </div>

</div>