config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root 'projects#index'

  resources :projects do
    resources :categories do
      resources :products
    end

    resources :bill_types
    resources :incomes

    resources :bills do
      resources :bill_rows
    end
  end

  resources :contacts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord

  has_many :incomes
  has_many :categories
  has_many :bill_types
  has_many :bills

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @bills_count = @project.bills.count
    @bills_total_amount = @project.bills.calculate(:sum, :total_amount)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    @bills_total_amount = @project.bills.calculate(:sum, :total_amount)
    @bills_count = @project.bills.count
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(
          :name, 'init_date(1i)', 'init_date(2i)', 'init_date(3i)', 'final_date(1i)', 'final_date(2i)', 'final_date(3i)'
      )
      {
          name: params[:project][:name],
          init_date: get_init_date(params[:project]),
          final_date: get_final_date(params[:project]),
          total: 0
      }
    end

    def get_init_date(params)
      Date.civil(params['init_date(1i)'].to_i, params['init_date(2i)'].to_i, params['init_date(3i)'].to_i)
    end

    def get_final_date(params)
      Date.civil(params['final_date(1i)'].to_i, params['final_date(2i)'].to_i, params['final_date(3i)'].to_i)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def number_of_incomes(project)
    project.incomes.count || 0
  end

end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :init_date %>
    <%= form.date_select :init_date %>
  </div>

  <div class="field">
    <%= form.label :final_date %>
    <%= form.date_select :final_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<div class='view-content'>

  <div class="title">
    <h1>Projects</h1>
  </div>

  <div class="table-projects-index">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Total Expenses</th>
          <th>Total Incomes</th>
          <th>Init date</th>
          <th>Final date</th>
          <th>Last update</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td><%= link_to project.name, project %></td>
            <td><%= project.total %></td>
            <td><%= project.total_incomes %></td>
            <td><%= project.init_date.strftime('%d/%m/%Y') %></td>
            <td><%= project.final_date %></td>
            <td><%= project.last_update %></td>
            <td><%= link_to 'Show', project %></td>
            <td><%= link_to 'Edit', edit_project_path(project) %></td>
            <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br>

  <%= link_to 'New Project', new_project_path %>
</div>

app/views/projects/new.html.erb
<div class="project_form">
  <h1>New Project</h1>

  <%= render 'form', project: @project %>

  <div class="project-form-field-back">
    <%= link_to 'Back', projects_path %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="project-data-container">

  <div class="project-info-section">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Name:</strong>
      <%= @project.name %>
    </p>

    <p>
      <strong>Total Expenses:</strong>
      <%= @project.total %>
    </p>

    <p>
      <strong>Total Incomes:</strong>
      <%= @project.total_incomes %>
    </p>

    <p>
      <strong>Init date:</strong>
      <%= @project.init_date.strftime('%d/%m/%Y') %>
    </p>

    <p>
      <strong>Final date:</strong>
      <%= @project.final_date.try(:strftime, ('%d/%m/%Y')) %>
    </p>

    <p>
      <strong>Last update:</strong>
      <%= @project.last_update.try(:strftime, ('%d/%m/%Y')) %>
    </p>

    <div class="info-section-bottons">
      <%= link_to 'Edit', edit_project_path(@project) %> |
      <%= link_to 'Back', projects_path %>
    </div>
  </div>

  <div class="project-data-section">
    <div class="bills-data">
      <div class="project-data-section-field">
        Bills total amount: <%= (@bills_total_amount || 0).to_s %>
      </div>
      <div class="project-data-section-field">
        <%= link_to "Bills: #{(@bills_count|| 0).to_s}", project_bills_path(@project) %>
      </div>
    </div>

    <div class="incomes-data">
      <div class="project-data-section-field">
        Incomes total amount: <%= (@project.total_incomes || 0).to_s %>
      </div>
      <div class="project-data-section-field">

        <%= link_to "Incomes: #{number_of_incomes(@project)}", project_incomes_path(@project) %>
      </div>
    </div>
  </div>

</div>