config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root 'projects#index'

  resources :projects do
    resources :categories do
      resources :products
    end

    resources :bill_types
    resources :incomes

    resources :bills do
      resources :bill_rows
    end
  end

  resources :contacts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord

  belongs_to :project
  has_many :products

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :set_project, only: [:show, :edit, :update, :destroy, :index, :new, :create]

  # GET /categories
  # GET /categories.json
  def index
    @categories = @project.categories
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @products = @category.products
    @product = Product.new
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to project_category_path(@project, @category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to project_category_path(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to project_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:project_id, :description, :name)
      {
          project_id: @project.id,
          description: params[:category][:description],
          name: params[:category][:name]
      }
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: @category, url: [@project, @category], local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_field :description %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>

<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', project_category_path(@project, @category) %> |
<%= link_to 'Back', project_categories_path(@project) %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="view-content">

  <div class="title">
    <h1>Categorias</h1>
  </div>

  <div class="table-categories-index">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= link_to category.name, project_category_path(@project, category) %></td>
            <td><%= link_to category.description, project_category_path(@project, category) %></td>
            <td><%= link_to 'Editar', edit_project_category_path(@project, category) %></td>
            <td><%= link_to 'Eliminar', project_category_path(@project.id, category), method: :delete, data: { confirm: 'Estas segur@?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>

  <%= link_to 'New Category', new_project_category_path %>
</div>

app/views/categories/new.html.erb
<div class="category_form">
  <h1>Nueva Categoria</h1>

  <%= render 'form', category: @category %>

  <div class="category-form-field-back">
    <%= link_to 'Back', project_categories_path %>
  </div>

</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<div class="category-show-section">
  <div class="category-info-section">
    <div class="view-content">

      <div class="title">Category: <%= @category.name %></div>
      <p>
        <strong>Project:</strong>
        <%= @category.project.name %>
      </p>

      <p>
        <strong>Name:</strong>
        <%= @category.name %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @category.description %>
      </p>

      <%= link_to 'Edit', edit_project_category_path(@category) %> |
      <%= link_to 'Back', project_categories_path %>
    </div>
  </div>

  <div class="category-product-section">
    <div class="table-products-index">
      <div class="category-product-section-title">Productos de <%= @category.name %></div>
      <table>
        <thead>
        <tr>
          <th>Name</th>
          <th>Notes</th>
          <th>Price</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.notes %></td>
            <td><%= product.price %></td>

            <td><%= link_to 'Show', project_category_product_path(@project, @category, product) %></td>
            <td><%= link_to 'Edit', edit_project_category_product_path(@project, @category, product) %></td>
            <td><%= link_to 'Destroy', project_category_product_path(@project, @category, product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="category-product-form">
      Agregar un producto nuevo:
      <%= render 'products/form', product: @product %>
    </div>
  </div>
</div>