config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root 'projects#index'

  resources :projects do
    resources :categories do
      resources :products
    end

    resources :bill_types
    resources :incomes

    resources :bills do
      resources :bill_rows
    end
  end

  resources :contacts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :category
  has_many :bill_rows

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_project_and_category

  # GET /products
  # GET /products.json
  def index
    @products = @category.products
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html {
          redirect_to project_category_path(@project, @category),
                      notice: 'Product was successfully created.'
        }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html {
          redirect_to project_category_path(@project, @category),
                      notice: 'Product was successfully updated.'
        }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to project_category_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def set_project_and_category
      @project = Project.find(params[:project_id])
      @category = Category.find(params[:category_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:category_id, :price, :name, :notes)
      {
          category_id: @category.id,
          price: params[:product][:price],
          name: params[:product][:name],
          notes: params[:product][:notes]
      }
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: @product,  url: [@project, @category, @product], local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="product-field">
    <div class="field">
      <%= form.label :price %>
      <%= form.text_field :price %>
    </div>
  </div>

  <div class="product-field">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  </div>

  <div class="product-field">
    <div class="field">
      <%= form.label :notes %>
      <%= form.text_field :notes %>
    </div>
  </div>


  <div class="product-field">
    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', project_category_product_path(@project, @category, @product) %> |
<%= link_to 'Back', project_category_products_path(@project, @category, @product) %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="view-content">
  <div class="title">
    <h1>Products for <%= @category.name %>'s Category </h1>
  </div>

  <div class="table-products-index">

    <table>
      <thead>
        <tr>
          <th>Price</th>
          <th>Name</th>
          <th>Notes</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.price %></td>
            <td><%= product.name %></td>
            <td><%= product.notes %></td>
            <td><%= link_to 'Show', project_category_product_path(@project, @category, product) %></td>
            <td><%= link_to 'Edit', edit_project_category_product_path(@project, @category, product) %></td>
            <td><%= link_to 'Destroy', project_category_product_path(@project, @category, product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>

  <%= link_to 'New Product', new_project_category_product_path %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', project_category_products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @product.notes %>
</p>

<%= link_to 'Edit', edit_project_category_product_path(@project, @category, @product) %> |
<%= link_to 'Back', project_category_products_path %>